p0_train:
  filepath: data/randomtraj_p0.pkl.train
  x_range: 
    - [-2, 2]
    - [-2, 2]
  u_range:
    - [-1.0, 1.0]
  param: 
    - 1.0
    - 0.05
  dt: 0.001
  nsample: 10000
  nstep: 15


p0_val:
  filepath: data/randomtraj_p0.pkl.val
  x_range: 
    - [-2, 2]
    - [-2, 2]
  u_range:
    - [-1.0, 1.0]
  param: 
    - 1.0
    - 0.05
  dt: 0.001
  nsample: 10000
  nstep: 15
