model_args:
  modeltype: 'standard'
  state:
    lifting: 'snmlp'
    args:
      nndims: [1, 64, 64, 32, 32, 3]
      normalize_hidden: True
      normalize_output: False
  normalization :
    x_range:
      - [-2.0, 2.0]
    dt: 0.001
  
fit_args:
  num_epochs: 50000
  learning_rate: 0.0001
  batch_size: 256
  nstep: 10
  decay: 0.8
  robust: 
  l2_weight: 0.0
  invariance_weight: 0.0
  unfold: True
  savepath: 'save/standard_p0.pt'
  trainset: 'data/randomtraj_p0.pkl.train'
  valset: 'data/randomtraj_p0.pkl.val'


