p0_train:
  filepath: data/randomtraj_p0.pkl.train
  x_range: 
    - [-2, 2]
  param: 
    - 1.0
  dt: 0.001
  nsample: 10000
  nstep: 15


p0_val:
  filepath: data/randomtraj_p0.pkl.val
  x_range: 
    - [-2, 2]
  param: 
    - 0.95
  dt: 0.001
  nsample: 10000
  nstep: 15
